---
engines:
  fixme:
    enabled: true
ratings:
  paths: []
exclude_paths: []
---
engines:
  eslint:
    enabled: true
ratings:
  paths:
  - lib/**/*.js"
  - test/**/*.js"
exclude_paths:
- test/**/*
